version: "3.8"
services:
  api:
    build: .
    depends_on: 
      - "db"
    ports: 
      - "8080:8080"
    expose:
      - 8080
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bestWorstBlog
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    command: sh -c 'while ! nc -z db 5432; do sleep 1; done; java -jar /app.jar'
  db:
    image: "postgres:13-alpine"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bestWorstBlog
    ports: 
      - "5432:5432"